### ISSUE TITLE
CI Build #20191015.1 failed

### ISSUE THREAD

**Issue by devpro** [devpro/withywoods#6]
Test: **AspNetCoreApiSampleSwaggerResourceGet_ReturnsHttpOk**
Failing build: 20191014.1

Build link: [dev.azure.com/devprofr](https://dev.azure.com/devprofr/open-source/_build/results?buildId=185&view=ms.vss-test-web.build-test-results-tab&runId=1000160&resultId=100020&paneView=debug)

Steps to reproduce:

- Execute `dotnet build`
- Execute `dotnet test`, expected: success, result: failure (1 test)

Error detail:
> System.InvalidOperationException : session not created: Chrome version must be between 70 and 73
>   (Driver info: chromedriver=73.0.3683.68 (47787ec04b6e38e22703e856e101e840b65afe72),platform=Windows NT 10.0.14393 x86_64) (SessionNotCreated)
>    at OpenQA.Selenium.Remote.RemoteWebDriver.UnpackAndThrowOnError(Response errorResponse)
>    at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary 2 parameters)
>    at OpenQA.Selenium.Remote.RemoteWebDriver.StartSession(ICapabilities desiredCapabilities)
>    at OpenQA.Selenium.Remote.RemoteWebDriver..ctor(ICommandExecutor commandExecutor, ICapabilities desiredCapabilities)
>    at OpenQA.Selenium.Chrome.ChromeDriver..ctor(ChromeDriverService service, ChromeOptions options, TimeSpan commandTimeout)
>    at OpenQA.Selenium.Chrome.ChromeDriver..ctor(String chromeDriverDirectory, ChromeOptions options, TimeSpan commandTimeout)
>    at Withywoods.AspNetCoreApiSample.IntegrationTests.Resources.SwaggerResourceTest..ctor(LocalServerFactory 1 server) in \test\AspNetCoreApiSample.IntegrationTests\Resources\SwaggerResourceTest.cs:line 31

**Comment by devpro** [comment]
Fixed with PR devpro/withywoods/pull/7

**Comment by devpro** [comment]
Fixed with PR /pull/7
