### ISSUE TITLE
CI Build #20191016.1 failed

### ISSUE THREAD

**Issue by devpro** [devpro/withywoods#9]
Test: **AspNetCoreApiSampleSwaggerResourceGet_ReturnsHttpOk**
Failing build: [20191016.1](https://dev.azure.com/devprofr/open-source/_build/results?buildId=193)

Steps to reproduce: not reproductible locally

Error detail:

> ##[error][xUnit.net 00:00:24.75]     AspNetCoreApiSampleSwaggerResourceGet_ReturnsHttpOk [FAIL]
> [xUnit.net 00:00:24.75]       System.InvalidOperationException : session not created: This version of ChromeDriver only supports Chrome version 77 (SessionNotCreated)
> [xUnit.net 00:00:24.75]       Stack Trace:
> [xUnit.net 00:00:24.75]            at OpenQA.Selenium.Remote.RemoteWebDriver.UnpackAndThrowOnError(Response errorResponse)
> [xUnit.net 00:00:24.75]            at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
> [xUnit.net 00:00:24.75]            at OpenQA.Selenium.Remote.RemoteWebDriver.StartSession(ICapabilities desiredCapabilities)
> [xUnit.net 00:00:24.76]            at OpenQA.Selenium.Remote.RemoteWebDriver..ctor(ICommandExecutor commandExecutor, ICapabilities desiredCapabilities)
> [xUnit.net 00:00:24.76]            at OpenQA.Selenium.Chrome.ChromeDriver..ctor(ChromeDriverService service, ChromeOptions options, TimeSpan commandTimeout)
> [xUnit.net 00:00:24.76]            at OpenQA.Selenium.Chrome.ChromeDriver..ctor(String chromeDriverDirectory, ChromeOptions options, TimeSpan commandTimeout)
> [xUnit.net 00:00:24.76]         D:\a\1\s\test\AspNetCoreApiSample.IntegrationTests\Resources\SwaggerResourceTest.cs(31,0): at Withywoods.AspNetCoreApiSample.IntegrationTests.Resources.SwaggerResourceTest..ctor(LocalServerFactory`1 server)

**Comment by devpro** [comment]
Fixed with PR devpro/withywoods#10
